tests:
  - '**/*.spec.js'

github_actions:
  - '.github/workflows/*'

vuex:
  - 'src/store/**/*.ts'

plugins:
  - 'src/plugins/**/*.ts'

vue:
  - '**/*.vue'

docker:
  - 'Dockerfile*'

ui:
  - any:
      ['src/components/**/*.vue', 'src/layouts/**/*.vue', 'src/pages/**/*.vue']
