tests:
  - '**/*.spec.js'

github_actions:
  - '.github/workflows/*'

vuex:
  - 'frontend/store/**/*.ts'

plugins:
  - 'frontend/plugins/**/*.ts'

vue:
  - '**/*.vue'

docker:
  - 'Dockerfile*'

ui:
  - any:
      [
        'frontend/components/**/*.vue',
        'frontend/layouts/**/*.vue',
        'frontend/pages/**/*.vue'
      ]
