tests:
  - '**/*.spec.js'

github_actions:
  - '.github/workflows/*'

vuex:
  - 'client/store/**/*.ts'

plugins:
  - 'client/plugins/**/*.ts'

vue:
  - '**/*.vue'

docker:
  - 'Dockerfile*'

ui:
  - any:
      [
        'client/components/**/*.vue',
        'client/layouts/**/*.vue',
        'client/pages/**/*.vue'
      ]
