name: Automation 🤖

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  comment:
    name: Create system comments 🖥️
    runs-on: ubuntu-latest
    steps:
      - name: Create job summary and add to environment
        run: |
          echo -e '## Cloudflare Pages deployment' >> $GITHUB_STEP_SUMMARY
          echo -e '\n' >> $GITHUB_STEP_SUMMARY
          echo '| **Latest commit**       	|       ``${{ github.sha }}``      	|' >> $GITHUB_STEP_SUMMARY
          echo '|-------------------------	|:----------------------------:	|' >> $GITHUB_STEP_SUMMARY
          echo '| **Status**              	| 🔄 Deploying...                  |' >> $GITHUB_STEP_SUMMARY
          echo '| **Preview URL**         	| Not available yet            	|' >> $GITHUB_STEP_SUMMARY
          echo '| **Branch Preview URL:** 	| https://${{ github.head_ref }}.jf-vue.pages.dev 	|' >> $GITHUB_STEP_SUMMARY
          echo -e '\n' >> $GITHUB_STEP_SUMMARY
          echo '<!--- CFPages deployment marker --->' >> $GITHUB_STEP_SUMMARY
          echo 'job_summary=$GITHUB_STEP_SUMMARY' >> $GITHUB_ENV

      - name: Create CF Pages deployment comment
        uses: thollander/actions-comment-pull-request@v1.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: ${{ env.job_summary }}
          comment_includes: '<!--- CFPages deployment marker --->'

  project:
    name: Project board 📊
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.2
        if: ${{ github.event_name == 'pull_request_target' }}
        continue-on-error: true
        with:
          project: Ongoing development
          column: In progress
          repo-token: ${{ secrets.JF_BOT_TOKEN }}

  label:
    name: Labeling 🏷️
    runs-on: ubuntu-latest
    steps:
      - name: Label PR depending on modified files
        uses: actions/labeler@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        continue-on-error: true
        with:
          repo-token: '${{ secrets.JF_BOT_TOKEN }}'

      - name: Check all PRs for merge conflicts ⛔
        uses: eps1lon/actions-label-merge-conflict@v2.1.0
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
