name: Build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ssr:
    name: Build SSR (Node ${{ matrix.node }} - ${{ matrix.architecture }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
        architecture:
          - x64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node_modules
        uses: actions/cache@v2.1.5
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.architecture }}-node${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.architecture }}-node${{ matrix.node }}-npm-

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: npm run build

  static:
    name: Build static (Node ${{ matrix.node }} - ${{ matrix.architecture }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
        architecture:
          - x64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node_modules
        uses: actions/cache@v2.1.5
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.architecture }}-node${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.architecture }}-node${{ matrix.node }}-npm-

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: 'npm run build:static'
