name: Build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ssr:
    name: Build SSR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup node environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: npm run build

  static:
    name: Build static
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup node environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: 'npm run build:static'
