name: 'Label pull requests'
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        continue-on-error: true
        with:
          repo-token: '${{ secrets.JF_BOT_TOKEN }}'
