name: Code quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup node environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Run linter
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup node environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Run tests
        run: npm run test

      - name: Upload coverage
        uses: codecov/codecov-action@v2.0.1
