name: 'Merge Conflicts'

on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - synchronize
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v2.0.0
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.GH_TOKEN }}
