name: Pull Request Checks 👌🧪

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Lint 🔬
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v2.4.0

      - name: Setup node environment ⚙️
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies 📦
        run: npm ci --no-audit

      - name: Run linter ✏️
        run: npm run lint

  test:
    name: Test 🧫
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Setup node environment ⚙️
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies 📦
        run: npm ci --no-audit

      - name: Run tests 🧪
        run: npm run test

      - name: Upload coverage ⬆️
        uses: codecov/codecov-action@v2.0.3

  build:
    name: Build 🛠️
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v2.4.0

      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v1.2.0

      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v1.5.1

      - name: Build Docker image 🛠️
        uses: docker/build-push-action@v2.6.1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          load: true
          tags: |
            jellyfin/jellyfin-vue

      - name: Verify that Docker image runs 🧫
        run: docker run --rm jellyfin/jellyfin-vue
